blank_issues_enabled: false
contact_links:
  - name: ğŸŒ Documentation
    url: https://github.com/Annany2002/nebula-frontend#readme
    about: Refer to the official README for setup, configuration, and usage.
